app:
  log_level: info
gameserver:
  - ip: 127.0.0.1
    query_port: 25575
    rcon_password: yoursecurepasswordhere
    schedules:
      ###
      # SCHEDULES FOR SERVER UPDATES
      ###
      # cronjob 4:00 - server update
      - command: broadcast
        arguments: "Attention:_Daily_Server_Update_Check_At_4am!"
        every:
          - day:
            - at:
              - "03:55"
              - "Europe/Berlin"
          - day:
            - at:
              - "03:56"
              - "Europe/Berlin"
          - day:
            - at:
              - "03:57"
              - "Europe/Berlin"
          - day:
            - at:
              - "03:58"
              - "Europe/Berlin"
          - day:
            - at:
              - "03:59"
              - "Europe/Berlin"
      # save game
      - command: Save
        every:
          - day:
            - at:
              - "03:59"
              - "Europe/Berlin"
      # cronjob 13:00 - server update
      - command: broadcast
        arguments: "Attention:_Daily_Server_Update_Check_At_1pm!"
        every:
          - day:
            - at:
              - "12:55"
              - "Europe/Berlin"
          - day:
            - at:
              - "12:56"
              - "Europe/Berlin"
          - day:
            - at:
              - "12:57"
              - "Europe/Berlin"
          - day:
            - at:
              - "12:58"
              - "Europe/Berlin"
          - day:
            - at:
              - "12:59"
              - "Europe/Berlin"
      # save game
      - command: Save
        every:
          - day:
            - at:
              - "12:59"
              - "Europe/Berlin"
      ###
      # SCHEDULES FOR SERVER RESTARTS
      ###
      # cronjob 12:00 - server restart
      - command: broadcast
        arguments: "Attention:_Automated_Server_Restart_At_12am_incoming!"
        every:
          - day:
            - at:
              - "11:55"
              - "Europe/Berlin"
          - day:
            - at:
              - "11:56"
              - "Europe/Berlin"
          - day:
            - at:
              - "11:57"
              - "Europe/Berlin"
          - day:
            - at:
              - "11:58"
              - "Europe/Berlin"
          - day:
            - at:
              - "11:59"
              - "Europe/Berlin"
      # save game
      - command: Save
        every:
          - day:
            - at:
              - "11:59"
              - "Europe/Berlin"
      # shutdown the game with the internal timer first to avoid corrupt save games
      - command: Shutdown
        arguments: "55 Server_Reboot_In_55_Seconds!"
        every:
          - day:
            - at:
              - "11:59"
              - "Europe/Berlin"
      ###
      # CUSTOM FUNCTIONS
      ###
      # welcome new players
      - command: ShowPlayers
        callback: playerstatus.announce_player
        every:
          - seconds: 5
      ###
      # ANNOUNCEMENTS
      ###
      # announcement every hour (e.g. 12:15, 13:15, 14:15,...)
      - command: broadcast
        arguments: "Info:_Regular_Restarts:_12am_For_Performance_Reasons!"
        every:
          - hour:
            - at: ":15"
      # announcement every hour (e.g. 12:16, 13:16, 14:16,...)
      - command: broadcast
        arguments: "Info:_Update_Checks:_4am_and_1pm_Every_Day!"
        every:
          - hour:
            - at: ":16"
      # announcement every hour (e.g. 12:30, 13:30, 14:30,...)
      - command: broadcast
        arguments: "Visit_palworld.party_And_Join_Our_Discord_:)"
        every:
          - hour:
            - at: ":30"
